# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: 'user@gmail.com',password:"user123!")


Room.create(room_name: 'L1_M01', room_type: "Meeting Room",floor:1,capacities: 5)
Room.create(room_name: 'L1_M02', room_type: "Meeting Room",floor:1,capacities: 5)
Room.create(room_name: 'L1_M03', room_type: "Meeting Room",floor:1,capacities: 6)
Room.create(room_name: 'L1_M04', room_type: "Meeting Room",floor:1,capacities: 6)
Room.create(room_name: 'L1_M05', room_type: "Meeting Room",floor:1,capacities: 8)
Room.create(room_name: 'L1_M06', room_type: "Meeting Room",floor:1,capacities: 8)
Room.create(room_name: 'L1_M07', room_type: "Meeting Room",floor:1,capacities: 7)
Room.create(room_name: 'L1_M08', room_type: "Meeting Room",floor:1,capacities: 10)
Room.create(room_name: 'L1_M09', room_type: "Meeting Room",floor:1,capacities: 6)
Room.create(room_name: 'L1_M10', room_type: "Meeting Room",floor:1,capacities: 8)
Room.create(room_name: 'L1_M11', room_type: "Meeting Room",floor:1,capacities: 8)
Room.create(room_name: 'L1_M12', room_type: "Meeting Room",floor:1,capacities: 7)
Room.create(room_name: 'L1_M13', room_type: "Meeting Room",floor:1,capacities: 10)
Room.create(room_name: 'L1_M14', room_type: "Meeting Room",floor:1,capacities: 5)
Room.create(room_name: 'L1_M15', room_type: "Meeting Room",floor:1,capacities: 5)


Room.create(room_name: 'L1_F01', room_type: "Facility Room",floor:1,capacities: 8)
Room.create(room_name: 'L1_F02', room_type: "Facility Room",floor:1,capacities: 7)
Room.create(room_name: 'L1_F03', room_type: "Facility Room",floor:1,capacities: 10)
Room.create(room_name: 'L1_F04', room_type: "Facility Room",floor:1,capacities: 9)
Room.create(room_name: 'L1_F05', room_type: "Facility Room",floor:1,capacities: 5)
Room.create(room_name: 'L1_F06', room_type: "Facility Room",floor:1,capacities: 5)
Room.create(room_name: 'L1_F07', room_type: "Facility Room",floor:1,capacities: 7)
Room.create(room_name: 'L1_F08', room_type: "Facility Room",floor:1,capacities: 6)
Room.create(room_name: 'L1_F09', room_type: "Facility Room",floor:1,capacities: 8)
Room.create(room_name: 'L1_F10', room_type: "Facility Room",floor:1,capacities: 7)
Room.create(room_name: 'L1_F11', room_type: "Facility Room",floor:1,capacities: 10)
Room.create(room_name: 'L1_F12', room_type: "Facility Room",floor:1,capacities: 9)
Room.create(room_name: 'L1_F13', room_type: "Facility Room",floor:1,capacities: 6)
Room.create(room_name: 'L1_F14', room_type: "Facility Room",floor:1,capacities: 5)
Room.create(room_name: 'L1_F15', room_type: "Facility Room",floor:1,capacities: 6)



Room.create(room_name: 'L2_M01', room_type: "Meeting Room",floor:2,capacities: 5)
Room.create(room_name: 'L2_M02', room_type: "Meeting Room",floor:2,capacities: 7)
Room.create(room_name: 'L2_M03', room_type: "Meeting Room",floor:2,capacities: 10)
Room.create(room_name: 'L2_M04', room_type: "Meeting Room",floor:2,capacities: 8)
Room.create(room_name: 'L2_M05', room_type: "Meeting Room",floor:2,capacities: 6)
Room.create(room_name: 'L2_M06', room_type: "Meeting Room",floor:2,capacities: 10)
Room.create(room_name: 'L2_M07', room_type: "Meeting Room",floor:2,capacities: 9)
Room.create(room_name: 'L2_M08', room_type: "Meeting Room",floor:2,capacities: 10)
Room.create(room_name: 'L2_M09', room_type: "Meeting Room",floor:2,capacities: 6)
Room.create(room_name: 'L2_M10', room_type: "Meeting Room",floor:2,capacities: 7)

Room.create(room_name: 'L2_F01', room_type: "Facility Room",floor:2,capacities: 7)
Room.create(room_name: 'L2_F02', room_type: "Facility Room",floor:2,capacities: 5)
Room.create(room_name: 'L2_F03', room_type: "Facility Room",floor:2,capacities: 8)
Room.create(room_name: 'L2_F04', room_type: "Facility Room",floor:2,capacities: 9)
Room.create(room_name: 'L2_F05', room_type: "Facility Room",floor:2,capacities: 10)
Room.create(room_name: 'L2_F06', room_type: "Facility Room",floor:2,capacities: 6)
Room.create(room_name: 'L2_F07', room_type: "Facility Room",floor:2,capacities: 8)
Room.create(room_name: 'L2_F08', room_type: "Facility Room",floor:2,capacities: 10)
Room.create(room_name: 'L2_F09', room_type: "Facility Room",floor:2,capacities: 7)
Room.create(room_name: 'L2_F10', room_type: "Facility Room",floor:2,capacities: 5)

Room.create(room_name: 'L3_M01', room_type: "Meeting Room",floor:3,capacities: 8)
Room.create(room_name: 'L3_M02', room_type: "Meeting Room",floor:3,capacities: 7)
Room.create(room_name: 'L3_M03', room_type: "Meeting Room",floor:3,capacities: 5)
Room.create(room_name: 'L3_M04', room_type: "Meeting Room",floor:3,capacities: 6)
Room.create(room_name: 'L3_M05', room_type: "Meeting Room",floor:3,capacities: 9)
Room.create(room_name: 'L3_M06', room_type: "Meeting Room",floor:3,capacities: 7)
Room.create(room_name: 'L3_M07', room_type: "Meeting Room",floor:3,capacities: 9)
Room.create(room_name: 'L3_M08', room_type: "Meeting Room",floor:3,capacities: 10)
Room.create(room_name: 'L3_M09', room_type: "Meeting Room",floor:3,capacities: 10)
Room.create(room_name: 'L3_M10', room_type: "Meeting Room",floor:3,capacities: 6)

Room.create(room_name: 'L3_F01', room_type: "Facility Room",floor:3,capacities: 7)
Room.create(room_name: 'L3_F02', room_type: "Facility Room",floor:3,capacities: 8)
Room.create(room_name: 'L3_F03', room_type: "Facility Room",floor:3,capacities: 9)
Room.create(room_name: 'L3_F04', room_type: "Facility Room",floor:3,capacities: 10)
Room.create(room_name: 'L3_F05', room_type: "Facility Room",floor:3,capacities: 5)
Room.create(room_name: 'L3_F06', room_type: "Facility Room",floor:3,capacities: 6)
Room.create(room_name: 'L3_F07', room_type: "Facility Room",floor:3,capacities: 8)
Room.create(room_name: 'L3_F08', room_type: "Facility Room",floor:3,capacities: 10)